---
########################################
# ğŸ› ï¸ ConfigMap - Key-Value Config Data #
########################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home-config
  namespace: adguard-home
data:
  TZ: "Australia/Melbourne"
