---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: adguard-home
  namespace: flux-system
resources:
  - configmap-adguard-home.yaml
  - deployment-adguard-home.yaml
  - dns-endpoint-adguard-home.yaml
  - ingress-adguard-home.yaml
  - kustomization.yaml
  - pvc-adguard-home.yaml
  - service-adguard-home.yaml
