---
########################################
# ðŸ§© Kustomization - Overlay Control   #
########################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
resources:
  - helmrelease-cloudnative-pg.yaml
  - helm-values-override-cloudnative-pg.yaml
