---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: reflector
  namespace: flux-system
resources:
  - helmrelease-reflector.yaml
  - helm-values-override-reflector.yaml
