---
########################################
# ðŸ§© Kustomization - Overlay Control   #
########################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
resources:
  - dns-endpoint-longhorn.yaml
  - helmrelease-longhorn.yaml
  - helm-values-override-longhorn.yaml
  - ingress-longhorn-dashboard.yaml
  - externalsecret-longhorn-garage-secret.yaml
