---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ssl-certificates
  namespace: flux-system
resources:
  - cert-wildcard-islandbytes-net-prod.yaml
  - cert-traefik-islandbytes-net-prod.yaml
  - cert-longhorn-islandbytes-net-prod.yaml
  - cert-adguard-islandbytes-net-prod.yaml
