---
#############################################
# üîê ExternalSecret - External Secret Spec  #
#############################################
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-adguard-config
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao                                 # your existing ClusterSecretStore
  target:
    name: external-dns-adguard-config             # the K8s Secret that apps will consume
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: k8s/infra_apps/external-dns/adguard-config
