---
########################################
# ðŸ§© Kustomization - Overlay Control   #
########################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
resources:
  - helmrelease-external-dns.yaml
  - helm-values-override-external-dns.yaml
  - externalsecret-external-dns-adguard-config.yaml
