---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: shared-secrets
  namespace: flux-system
resources:
  - externalsecret-gluetun-vpn-credentials.yaml
