---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: adguard-sync
  namespace: flux-system
resources:
  - configmap-adguard-home-sync.yaml
  - deployment-adguard-home-sync.yaml
  - externalsecret-adguard-home-sync.yaml
  - service-adguard-home-sync.yaml.
