---
########################################
# ðŸ§© Kustomization - Overlay Control   #
########################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: redis-operator
  namespace: flux-system
resources:
  - helmrelease-redis-operator.yaml
  - helm-values-override-redis-operator.yaml
