---
####################################
# â›µ Helm Values - Chart Settings  #
####################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-values-override-cert-manager
  namespace: cert-manager
data:
  values.yaml: |-
    # Cert Manager default values
    installCRDs: true
    replicaCount: 3
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 9.9.9.9
