---
########################################
# ðŸ§© Kustomization - Overlay Control   #
########################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nfs-volumes
  namespace: flux-system
resources:
  - pvc-nfs-downloads.yaml
  - pvc-nfs-multimedia.yaml
  - pv-nfs-downloads.yaml
  - pv-nfs-multimedia.yaml
