---
#######################################
# ðŸ§© Kustomization - FluxCD Resource  #
#######################################
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
resources:
  - adguard-home/
  - adguard-sync/
